### ISSUE TITLE
Can't build on OS X 10.11

### ISSUE THREAD

**Issue by sdogruyol** [ysbaddaden/frost#1]
`make run` fails with the error

```
Assertion failed: ((i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"), function init, file /tmp/llvm20151214-69554-hagc7s/llvm-3.6.2.src/lib/IR/Instructions.cpp, line 281.
```

**Comment by ysbaddaden** [comment]
Damn. That error is weird. LLVM just flat out fails. Thought I won't be able to debug anything until january (no OS X at hand).

**Comment by sdogruyol** [comment]
Is there any lead that you can give?

**Comment by ysbaddaden** [comment]
No, I'm speechless with this error. It feels so low level... I admit I never tried Frost on OS X, only on Linux (Ubuntu), and only ever hit the postgres linking bug.

**Comment by vjdhama** [comment]
Exact same error for me also on `OSX 10.10.5`.

**Comment by sdogruyol** [comment]
@vjdhama could you please tell your LLVM version

**Comment by ysbaddaden** [comment]
BTW: I have LLVM 3.6 installed myself (along with 3.5, but 3.6 should take precedence).

**Comment by vjdhama** [comment]
@sdogruyol I have LLVM `3.6.2`.

**Comment by asterite** [comment]
Same error here. Probably a compiler bug, but it's mysterious that it doesn't happen on Linux

**Comment by ysbaddaden** [comment]
I checked, and I have LLVM 3.6.0 on my Ubuntu Trusty (newer releases have 3.6.2). That may explain why it works on _my_ Linux, but not on OS X.

**Comment by sdogruyol** [comment]
Why don't we use Travis?

**Comment by ysbaddaden** [comment]
I'll configure Travis when I have some free time behind a computer. I'm still in the Alps for a week :-)

**Comment by shyammohankanojia** [comment]
+1

Same Error for me too :+1: 

Assertion failed: ((i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"), function init, file /tmp/llvm20151214-56015-1irriwq/llvm-3.6.2.src/lib/IR/Instructions.cpp, line 281.
make: **\* [bin/crapp] Abort trap: 6

**Comment by ysbaddaden** [comment]
I configured Travis CI and OS X fails to run the test suite with the same [LLVM assertion error](https://travis-ci.org/ysbaddaden/frost/jobs/99027765). That really goes far beyond my knowledge —it could at least print out some debug information. I don't even know where to start looking for what's may cause this compiler bug...

And, as you can see, Linux is fine ...

**Comment by ysbaddaden** [comment]
I found a reference: http://stackoverflow.com/questions/15777182/how-to-debug-llvm3-2-plugin-assertion-error which just says to actually _read_ the failing assertion. It looks like the generated LLVM code generated a bad function: either it has more arguments than declared, or the arg type is different than expected.

**Comment by asterite** [comment]
I'm investigating the bug, I still didn't find the cause. However, the problem seems to be in `routes.cr`. If the routes definition is empty the bug is triggered. So maybe for now, just as a workaround, provide at least a root route so it doesn't crash?

**Comment by ysbaddaden** [comment]
Thanks @asterite for looking up the bug!

I did have a bug with empty routes (invalid generated code), which I fixed here: 
https://github.com/ysbaddaden/frost/commit/ae8de4c09d05c3417518831f99b4b8399ec15826#diff-a2fe33bcba81199382736955b3235c66

I recall I had to make a tiny change for the compiler to not fail (maybe it crashed, I'm not sure):
https://github.com/ysbaddaden/frost/commit/ae8de4c09d05c3417518831f99b4b8399ec15826#diff-fd55d7e021ca3b43c4d84db1fcbcc95aR37

I thought, at the time, to add an empty route, but it's complex: a route must map to a controller/action or the app won't compile!

**Comment by asterite** [comment]
For now, just as a temporary workaround, you can write `typeof(Route.new("foo", "bar", "bas", "lala", nil))` somewhere (for example in route_set.cr). The main issue has to do with Route not being instantiated and the compiler not knowing its instance variables. It's kind of hard to explain, but of course this will disappear once everything has a type. As a small example, check this code:

``` crystal
class Foo
  def foo
    @foo
  end
end

([] of Foo).each do |foo|
  puts foo.foo
end
```

What's the type of `foo.foo`? The compiler has to type it, but it can't because it doesn't know the type of `@foo`. For now the compiler mostly workarounds this in many ways, and it's a real headache to deal with these issues. In the new compiler approach this can't happen anymore because the compiler will be able to figure out all types.

**Comment by ysbaddaden** [comment]
Thanks @asterite. I understand the problem, and this is one more reason for typed instance variables! I'll cross my fingers while Travis runs the test suite on OS X :-)

**Comment by ysbaddaden** [comment]
Damn, it didn't pass. I shall add it somewhere else, maybe.

**Comment by sdogruyol** [comment]
Did this pass ?

**Comment by sdogruyol** [comment]
Oh just saw your comment :cry:

**Comment by ysbaddaden** [comment]
Still no luck :'(

**Comment by vjdhama** [comment]
Any update on this issue?

**Comment by ysbaddaden** [comment]
Coming back from vacations, I got access to an OS X VM. I finally reproduced and tracked down the problem in the test suite to https://github.com/ysbaddaden/frost/blob/master/test/dispatcher_test.cr#L12

If I comment this line `raise "let's fail"`, then the test suite compiles and run on OSX, and almost passes (the test for the exception fails, of course).

**Comment by ysbaddaden** [comment]
Both errors are... unrelated? I mean the test suite error and the empty routes error. The solution @asterite provided did fix the problem raised in this issue, but didn't fix the test suite issue. See #2
